'use client';

import { useState } from 'react';
import { Student, CourseHistory, ProgramEnrollment, PriceType } from '@/types';
import { Input, Select, Button } from '@/components/ui';
import { useCourses, usePrograms } from '@/lib/hooks';
import { calculateAge, generateId } from '@/lib/utils';
import { PRICE_OPTIONS, formatCurrency } from '@/lib/constants/pricing';

interface StudentFormProps {
  onSubmit: (studentData: Omit<Student, 'id' | 'createdAt'>) => Promise<void>;
  onCancel?: () => void;
  initialData?: Student;
  isLoading?: boolean;
  apiErrors?: string[];
}

export function StudentForm({ onSubmit, onCancel, initialData, isLoading = false, apiErrors = [] }: StudentFormProps) {
  const { courses } = useCourses();
  const { programs } = usePrograms();

  const [formData, setFormData] = useState({
    firstName: initialData?.firstName || '',
    lastName: initialData?.lastName || '',
    email: initialData?.email || '',
    phone: initialData?.phone || '',
    parentEmail: initialData?.parentEmail || '',
    parentPhone: initialData?.parentPhone || '',
    dateOfBirth: initialData?.dateOfBirth || '',
    isReturningStudent: initialData?.isReturningStudent || false,
  });

  const [selectedPastCourses, setSelectedPastCourses] = useState<string[]>(
    initialData?.courseHistory.map((h) => h.courseId) || []
  );

  const [enrollInProgram, setEnrollInProgram] = useState(false);
  const [selectedProgram, setSelectedProgram] = useState<string>('');
  const [selectedBatch, setSelectedBatch] = useState<number>(1);
  const [selectedPriceType, setSelectedPriceType] = useState<PriceType>('FULL_PRICE');
  const [errors, setErrors] = useState<Record<string, string>>({});

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    const newErrors: Record<string, string> = {};

    if (!formData.firstName.trim()) newErrors.firstName = 'First name is required';
    if (!formData.lastName.trim()) newErrors.lastName = 'Last name is required';

    // Student email is now optional
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (formData.email.trim() && !emailRegex.test(formData.email)) {
      newErrors.email = 'Invalid email format';
    }

    // Student phone is now optional

    // Parent contact is now required
    if (!formData.parentEmail.trim()) newErrors.parentEmail = 'Parent email is required';
    if (formData.parentEmail.trim() && !emailRegex.test(formData.parentEmail)) {
      newErrors.parentEmail = 'Invalid parent email format';
    }
    if (!formData.parentPhone.trim()) newErrors.parentPhone = 'Parent phone is required';

    // Check enrollment and price type if enrolled in program
    if (enrollInProgram && !selectedProgram) {
      newErrors.selectedProgram = 'Please select a program';
    }
    if (enrollInProgram && selectedProgram && !selectedPriceType) {
      newErrors.selectedPriceType = 'Please select a pricing option';
    }

    if (Object.keys(newErrors).length > 0) {
      setErrors(newErrors);
      return;
    }

    // Build course history from selected courses
    const courseHistory: CourseHistory[] = selectedPastCourses.map((courseId) => {
      const course = courses.find((c) => c.id === courseId);
      return {
        id: '', // Will be generated by hook
        courseId,
        courseName: course?.name || '',
        completionStatus: 'COMPLETED',
        dateAdded: new Date().toISOString(),
      };
    });

    // Build program enrollments if student is enrolling in a program
    let programEnrollments: ProgramEnrollment[] = initialData?.programEnrollments || [];
    if (enrollInProgram && selectedProgram && selectedPriceType) {
      // Get the price amount for the selected price type
      const priceOption = PRICE_OPTIONS.find((opt) => opt.type === selectedPriceType);
      const priceAmount = priceOption?.amount || 60000;

      // Create enrollment with minimal data - will be created by the hook
      const newEnrollment = {
        id: generateId(),  // Generate a temporary ID for the form
        programId: selectedProgram,
        batchNumber: selectedBatch,
        enrollmentDate: new Date().toISOString(),
        status: 'ASSIGNED' as const,
        paymentStatus: 'CONFIRMED' as const,
        priceType: selectedPriceType,
        priceAmount,
      };
      programEnrollments = [...programEnrollments, newEnrollment as any];
    }

    await onSubmit({
      firstName: formData.firstName,
      lastName: formData.lastName,
      email: formData.email || undefined,
      phone: formData.phone || undefined,
      parentEmail: formData.parentEmail || undefined,
      parentPhone: formData.parentPhone || undefined,
      dateOfBirth: formData.dateOfBirth || undefined,
      isReturningStudent: formData.isReturningStudent,
      courseHistory,
      programEnrollments,
      // Only set paymentStatus if student has program enrollments, otherwise leave as PENDING (not displayed)
      paymentStatus: programEnrollments.length > 0 ? 'CONFIRMED' : 'PENDING',
    } as any);

    setErrors({});
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-4">
      {/* API Error Summary */}
      {apiErrors.length > 0 && (
        <div className="p-3 bg-red-50 border border-red-200 rounded text-red-700 text-sm">
          <p className="font-semibold">The following contacts are already in use:</p>
          <ul className="mt-1 ml-4 list-disc">
            {apiErrors.map((error, i) => (
              <li key={i}>{error}</li>
            ))}
          </ul>
        </div>
      )}

      {/* Validation Error Summary */}
      {Object.keys(errors).length > 0 && (
        <div className="p-3 bg-red-50 border border-red-200 rounded text-red-700 text-sm">
          <p className="font-semibold">Please fix the following errors:</p>
          <ul className="mt-1 ml-4 list-disc">
            {Object.values(errors).map((error, i) => (
              <li key={i}>{error}</li>
            ))}
          </ul>
        </div>
      )}

      {/* Personal Information Section */}
      <div className="bg-gray-50 p-4 rounded-lg border border-gray-200">
        <h3 className="font-semibold text-gray-900 mb-3">Personal Information</h3>

        <div className="grid grid-cols-2 gap-3">
          <Input
            label="First Name"
            value={formData.firstName}
            onChange={(e) => setFormData({ ...formData, firstName: e.target.value })}
            error={errors.firstName}
            placeholder="e.g., John"
          />
          <Input
            label="Last Name"
            value={formData.lastName}
            onChange={(e) => setFormData({ ...formData, lastName: e.target.value })}
            error={errors.lastName}
            placeholder="e.g., Doe"
          />
        </div>

        <div>
          <Input
            label="Date of Birth"
            type="date"
            value={formData.dateOfBirth}
            onChange={(e) => setFormData({ ...formData, dateOfBirth: e.target.value })}
            className="mt-3"
          />
          {formData.dateOfBirth && (
            <div className="mt-2 p-2 bg-blue-50 border border-blue-200 rounded">
              <p className="text-sm text-blue-900">
                <span className="font-semibold">Age:</span> {calculateAge(formData.dateOfBirth)} years old
              </p>
            </div>
          )}
        </div>
      </div>

      {/* Contact Information Section */}
      <div className="bg-gray-50 p-4 rounded-lg border border-gray-200">
        <h3 className="font-semibold text-gray-900 mb-3">Contact Information</h3>

        <Input
          label="Student Email (Optional)"
          type="email"
          value={formData.email}
          onChange={(e) => setFormData({ ...formData, email: e.target.value })}
          error={errors.email}
          placeholder="student@example.com"
        />

        <Input
          label="Student Phone (Optional)"
          type="tel"
          value={formData.phone}
          onChange={(e) => setFormData({ ...formData, phone: e.target.value })}
          placeholder="+1 (555) 123-4567"
          className="mt-3"
        />

        <Input
          label="Parent Email"
          type="email"
          value={formData.parentEmail}
          onChange={(e) => setFormData({ ...formData, parentEmail: e.target.value })}
          error={errors.parentEmail}
          placeholder="parent@example.com"
          className="mt-3"
        />

        <Input
          label="Parent Phone"
          type="tel"
          value={formData.parentPhone}
          onChange={(e) => setFormData({ ...formData, parentPhone: e.target.value })}
          error={errors.parentPhone}
          placeholder="+1 (555) 987-6543"
          className="mt-3"
        />
      </div>

      {/* Program Enrollment Section */}
      <div className="bg-purple-50 p-4 rounded-lg border border-purple-200">
        <label className="flex items-center gap-3 cursor-pointer">
          <input
            type="checkbox"
            checked={enrollInProgram}
            onChange={(e) => {
              setEnrollInProgram(e.target.checked);
              if (!e.target.checked) {
                setSelectedProgram('');
                setSelectedBatch(1);
              }
            }}
            className="w-5 h-5 text-purple-600 rounded focus:ring-2 focus:ring-purple-500"
          />
          <span className="font-semibold text-gray-900">Enroll in an upcoming program?</span>
        </label>

        {enrollInProgram && (
          <div className="mt-4 space-y-4">
            <div>
              <label className="block text-sm font-semibold text-gray-700 mb-2">Select Program</label>
              {programs.length === 0 ? (
                <p className="text-gray-500 text-sm">No programs available</p>
              ) : (
                <select
                  value={selectedProgram}
                  onChange={(e) => {
                    setSelectedProgram(e.target.value);
                    setSelectedBatch(1); // Reset batch to 1 when program changes
                  }}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-purple-500"
                >
                  <option value="">-- Select a program --</option>
                  {programs.map((program) => (
                    <option key={program.id} value={program.id}>
                      {program.name} - {program.season} {program.year}
                    </option>
                  ))}
                </select>
              )}
              {errors.selectedProgram && <p className="text-red-600 text-xs mt-1">{errors.selectedProgram}</p>}
            </div>

            {selectedProgram && (
              <div>
                <label className="block text-sm font-semibold text-gray-700 mb-2">Select Batch</label>
                {(() => {
                  const program = programs.find((p) => p.id === selectedProgram);
                  return (
                    <div className="space-y-2">
                      {Array.from({ length: program?.batches || 1 }, (_, i) => i + 1).map((batchNum) => (
                        <label key={batchNum} className="flex items-center gap-3 cursor-pointer">
                          <input
                            type="radio"
                            name="batch"
                            value={batchNum}
                            checked={selectedBatch === batchNum}
                            onChange={(e) => setSelectedBatch(parseInt(e.target.value))}
                            className="w-4 h-4 text-purple-600 rounded focus:ring-2 focus:ring-purple-500"
                          />
                          <span className="text-sm text-gray-900">Batch {batchNum}</span>
                        </label>
                      ))}
                    </div>
                  );
                })()}
              </div>
            )}

            {selectedProgram && (
              <div>
                <label className="block text-sm font-semibold text-gray-700 mb-3">Select Pricing Option</label>
                <div className="space-y-2">
                  {PRICE_OPTIONS.map((option) => (
                    <label key={option.type} className="flex items-start gap-3 p-3 border rounded-lg cursor-pointer hover:bg-purple-50" style={{borderColor: selectedPriceType === option.type ? '#9333ea' : '#d1d5db', backgroundColor: selectedPriceType === option.type ? '#f3e8ff' : '#ffffff'}}>
                      <input
                        type="radio"
                        name="priceType"
                        value={option.type}
                        checked={selectedPriceType === option.type}
                        onChange={(e) => setSelectedPriceType(e.target.value as PriceType)}
                        className="w-4 h-4 text-purple-600 rounded focus:ring-2 focus:ring-purple-500 mt-0.5"
                      />
                      <div className="flex-1">
                        <div className="flex justify-between items-center">
                          <span className="text-sm font-semibold text-gray-900">{option.label}</span>
                          <span className="text-lg font-bold text-purple-600">{formatCurrency(option.amount)}</span>
                        </div>
                        <p className="text-xs text-gray-600 mt-1">{option.description}</p>
                      </div>
                    </label>
                  ))}
                </div>
                {errors.selectedPriceType && <p className="text-red-600 text-xs mt-2">{errors.selectedPriceType}</p>}
              </div>
            )}
          </div>
        )}
      </div>

      {/* Returning Student Section */}
      <div className="bg-blue-50 p-4 rounded-lg border border-blue-200">
        <label className="flex items-center gap-3 cursor-pointer">
          <input
            type="checkbox"
            checked={formData.isReturningStudent}
            onChange={(e) => setFormData({ ...formData, isReturningStudent: e.target.checked })}
            className="w-5 h-5 text-blue-600 rounded focus:ring-2 focus:ring-blue-500"
          />
          <span className="font-semibold text-gray-900">Is this a returning student?</span>
        </label>

        {formData.isReturningStudent && (
          <div className="mt-4">
            <p className="text-sm text-gray-600 mb-3">
              Select courses this student has previously taken with us:
            </p>
            <div className="space-y-2 max-h-48 overflow-y-auto border border-gray-300 rounded-lg p-3 bg-white">
              {courses.length === 0 ? (
                <p className="text-gray-500 text-sm">No courses available</p>
              ) : (
                courses.map((course) => (
                  <label key={course.id} className="flex items-center gap-3 cursor-pointer">
                    <input
                      type="checkbox"
                      checked={selectedPastCourses.includes(course.id)}
                      onChange={(e) => {
                        if (e.target.checked) {
                          setSelectedPastCourses([...selectedPastCourses, course.id]);
                        } else {
                          setSelectedPastCourses(
                            selectedPastCourses.filter((id) => id !== course.id)
                          );
                        }
                      }}
                      className="w-4 h-4 text-blue-600 rounded"
                    />
                    <span className="text-sm text-gray-700">{course.name}</span>
                  </label>
                ))
              )}
            </div>
            <p className="text-xs text-gray-500 mt-2">
              💡 These courses are added to their history for reference only. Students still need to be enrolled in the current program.
            </p>
          </div>
        )}
      </div>

      {/* Action Buttons */}
      <div className="flex gap-3 pt-4 border-t border-gray-200">
        <Button type="submit" variant="primary" className="flex-1" disabled={isLoading}>
          {initialData ? 'Update Student' : 'Create Student'}
        </Button>
        {onCancel && (
          <Button type="button" variant="outline" className="flex-1" onClick={onCancel}>
            Cancel
          </Button>
        )}
      </div>
    </form>
  );
}
