'use client';

import { useState } from 'react';
import { Student, CourseHistory } from '@/types';
import { Input, Select, Button } from '@/components/ui';
import { useCourses } from '@/lib/hooks';
import { calculateAge } from '@/lib/utils';

interface StudentFormProps {
  onSubmit: (studentData: Omit<Student, 'id' | 'createdAt'>) => void;
  onCancel?: () => void;
  initialData?: Student;
  isLoading?: boolean;
}

export function StudentForm({ onSubmit, onCancel, initialData, isLoading = false }: StudentFormProps) {
  const { courses } = useCourses();

  const [formData, setFormData] = useState({
    firstName: initialData?.firstName || '',
    lastName: initialData?.lastName || '',
    email: initialData?.email || '',
    phone: initialData?.phone || '',
    parentEmail: initialData?.parentEmail || '',
    parentPhone: initialData?.parentPhone || '',
    dateOfBirth: initialData?.dateOfBirth || '',
    isReturningStudent: initialData?.isReturningStudent || false,
    paymentStatus: initialData?.paymentStatus || 'pending',
  });

  const [selectedPastCourses, setSelectedPastCourses] = useState<string[]>(
    initialData?.courseHistory.map((h) => h.courseId) || []
  );

  const [errors, setErrors] = useState<Record<string, string>>({});

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    const newErrors: Record<string, string> = {};

    if (!formData.firstName.trim()) newErrors.firstName = 'First name is required';
    if (!formData.lastName.trim()) newErrors.lastName = 'Last name is required';
    if (!formData.email.trim()) newErrors.email = 'Email is required';

    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (formData.email.trim() && !emailRegex.test(formData.email)) {
      newErrors.email = 'Invalid email format';
    }

    if (!formData.phone.trim()) newErrors.phone = 'Phone is required';

    if (Object.keys(newErrors).length > 0) {
      setErrors(newErrors);
      return;
    }

    // Build course history from selected courses
    const courseHistory: CourseHistory[] = selectedPastCourses.map((courseId) => {
      const course = courses.find((c) => c.id === courseId);
      return {
        id: '', // Will be generated by hook
        courseId,
        courseName: course?.name || '',
        completionStatus: 'completed',
        dateAdded: new Date().toISOString(),
      };
    });

    onSubmit({
      firstName: formData.firstName,
      lastName: formData.lastName,
      email: formData.email,
      phone: formData.phone,
      parentEmail: formData.parentEmail || undefined,
      parentPhone: formData.parentPhone || undefined,
      dateOfBirth: formData.dateOfBirth || undefined,
      isReturningStudent: formData.isReturningStudent,
      courseHistory: initialData?.courseHistory || courseHistory,
      programEnrollments: initialData?.programEnrollments || [],
      paymentStatus: formData.paymentStatus as 'pending' | 'confirmed' | 'completed',
    });

    setErrors({});
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-4">
      {/* Error Summary */}
      {Object.keys(errors).length > 0 && (
        <div className="p-3 bg-red-50 border border-red-200 rounded text-red-700 text-sm">
          <p className="font-semibold">Please fix the following errors:</p>
          <ul className="mt-1 ml-4 list-disc">
            {Object.values(errors).map((error, i) => (
              <li key={i}>{error}</li>
            ))}
          </ul>
        </div>
      )}

      {/* Personal Information Section */}
      <div className="bg-gray-50 p-4 rounded-lg border border-gray-200">
        <h3 className="font-semibold text-gray-900 mb-3">Personal Information</h3>

        <div className="grid grid-cols-2 gap-3">
          <Input
            label="First Name"
            value={formData.firstName}
            onChange={(e) => setFormData({ ...formData, firstName: e.target.value })}
            error={errors.firstName}
            placeholder="e.g., John"
          />
          <Input
            label="Last Name"
            value={formData.lastName}
            onChange={(e) => setFormData({ ...formData, lastName: e.target.value })}
            error={errors.lastName}
            placeholder="e.g., Doe"
          />
        </div>

        <div>
          <Input
            label="Date of Birth"
            type="date"
            value={formData.dateOfBirth}
            onChange={(e) => setFormData({ ...formData, dateOfBirth: e.target.value })}
            className="mt-3"
          />
          {formData.dateOfBirth && (
            <div className="mt-2 p-2 bg-blue-50 border border-blue-200 rounded">
              <p className="text-sm text-blue-900">
                <span className="font-semibold">Age:</span> {calculateAge(formData.dateOfBirth)} years old
              </p>
            </div>
          )}
        </div>
      </div>

      {/* Contact Information Section */}
      <div className="bg-gray-50 p-4 rounded-lg border border-gray-200">
        <h3 className="font-semibold text-gray-900 mb-3">Contact Information</h3>

        <Input
          label="Student Email"
          type="email"
          value={formData.email}
          onChange={(e) => setFormData({ ...formData, email: e.target.value })}
          error={errors.email}
          placeholder="student@example.com"
        />

        <Input
          label="Student Phone"
          type="tel"
          value={formData.phone}
          onChange={(e) => setFormData({ ...formData, phone: e.target.value })}
          error={errors.phone}
          placeholder="+1 (555) 123-4567"
          className="mt-3"
        />

        <Input
          label="Parent Email (Optional)"
          type="email"
          value={formData.parentEmail}
          onChange={(e) => setFormData({ ...formData, parentEmail: e.target.value })}
          placeholder="parent@example.com"
          className="mt-3"
        />

        <Input
          label="Parent Phone (Optional)"
          type="tel"
          value={formData.parentPhone}
          onChange={(e) => setFormData({ ...formData, parentPhone: e.target.value })}
          placeholder="+1 (555) 987-6543"
          className="mt-3"
        />
      </div>

      {/* Payment Status */}
      <Select
        label="Payment Status"
        value={formData.paymentStatus}
        onChange={(e) => setFormData({ ...formData, paymentStatus: e.target.value })}
        options={[
          { value: 'pending', label: 'Pending - Awaiting Payment' },
          { value: 'confirmed', label: 'Confirmed - Payment Verified' },
          { value: 'completed', label: 'Completed' },
        ]}
      />

      {/* Returning Student Section */}
      <div className="bg-blue-50 p-4 rounded-lg border border-blue-200">
        <label className="flex items-center gap-3 cursor-pointer">
          <input
            type="checkbox"
            checked={formData.isReturningStudent}
            onChange={(e) => setFormData({ ...formData, isReturningStudent: e.target.checked })}
            className="w-5 h-5 text-blue-600 rounded focus:ring-2 focus:ring-blue-500"
          />
          <span className="font-semibold text-gray-900">Is this a returning student?</span>
        </label>

        {formData.isReturningStudent && (
          <div className="mt-4">
            <p className="text-sm text-gray-600 mb-3">
              Select courses this student has previously taken with us:
            </p>
            <div className="space-y-2 max-h-48 overflow-y-auto border border-gray-300 rounded-lg p-3 bg-white">
              {courses.length === 0 ? (
                <p className="text-gray-500 text-sm">No courses available</p>
              ) : (
                courses.map((course) => (
                  <label key={course.id} className="flex items-center gap-3 cursor-pointer">
                    <input
                      type="checkbox"
                      checked={selectedPastCourses.includes(course.id)}
                      onChange={(e) => {
                        if (e.target.checked) {
                          setSelectedPastCourses([...selectedPastCourses, course.id]);
                        } else {
                          setSelectedPastCourses(
                            selectedPastCourses.filter((id) => id !== course.id)
                          );
                        }
                      }}
                      className="w-4 h-4 text-blue-600 rounded"
                    />
                    <span className="text-sm text-gray-700">{course.name}</span>
                  </label>
                ))
              )}
            </div>
            <p className="text-xs text-gray-500 mt-2">
              💡 These courses are added to their history for reference only. Students still need to be enrolled in the current program.
            </p>
          </div>
        )}
      </div>

      {/* Action Buttons */}
      <div className="flex gap-3 pt-4 border-t border-gray-200">
        <Button type="submit" variant="primary" className="flex-1" disabled={isLoading}>
          {initialData ? 'Update Student' : 'Create Student'}
        </Button>
        {onCancel && (
          <Button type="button" variant="outline" className="flex-1" onClick={onCancel}>
            Cancel
          </Button>
        )}
      </div>
    </form>
  );
}
