import { UserRole } from '@/types';

// Permission definitions
export const PERMISSIONS = {
  // User management (Superadmin only)
  CREATE_USER: 'CREATE_USER',
  READ_USERS: 'READ_USERS',
  UPDATE_USER: 'UPDATE_USER',
  DELETE_USER: 'DELETE_USER',

  // Students (Staff can create/manage, others can view)
  CREATE_STUDENT: 'CREATE_STUDENT',
  READ_STUDENTS: 'READ_STUDENTS',
  UPDATE_STUDENT: 'UPDATE_STUDENT',
  DELETE_STUDENT: 'DELETE_STUDENT',

  // Courses (Admin+ can manage, Staff can view)
  CREATE_COURSE: 'CREATE_COURSE',
  READ_COURSES: 'READ_COURSES',
  UPDATE_COURSE: 'UPDATE_COURSE',
  DELETE_COURSE: 'DELETE_COURSE',

  // Programs (Admin+ can manage, Staff can view)
  CREATE_PROGRAM: 'CREATE_PROGRAM',
  READ_PROGRAMS: 'READ_PROGRAMS',
  UPDATE_PROGRAM: 'UPDATE_PROGRAM',
  DELETE_PROGRAM: 'DELETE_PROGRAM',

  // Classes (Admin+ can manage, Staff can view)
  CREATE_CLASS: 'CREATE_CLASS',
  READ_CLASSES: 'READ_CLASSES',
  UPDATE_CLASS: 'UPDATE_CLASS',
  DELETE_CLASS: 'DELETE_CLASS',
  ASSIGN_TEACHER: 'ASSIGN_TEACHER',

  // Teachers (Admin+ only)
  CREATE_TEACHER: 'CREATE_TEACHER',
  READ_TEACHERS: 'READ_TEACHERS',
  UPDATE_TEACHER: 'UPDATE_TEACHER',
  DELETE_TEACHER: 'DELETE_TEACHER',

  // Enrollments (Staff can create/manage, all can view)
  CREATE_ENROLLMENT: 'CREATE_ENROLLMENT',
  READ_ENROLLMENTS: 'READ_ENROLLMENTS',
  UPDATE_ENROLLMENT: 'UPDATE_ENROLLMENT',
  DELETE_ENROLLMENT: 'DELETE_ENROLLMENT',

  // Course History (Staff can create/manage, all can view)
  CREATE_COURSE_HISTORY: 'CREATE_COURSE_HISTORY',
  READ_COURSE_HISTORY: 'READ_COURSE_HISTORY',
  UPDATE_COURSE_HISTORY: 'UPDATE_COURSE_HISTORY',
  DELETE_COURSE_HISTORY: 'DELETE_COURSE_HISTORY',

  // Dashboard (all can view)
  VIEW_DASHBOARD: 'VIEW_DASHBOARD',

  // Waitlist (all can manage)
  MANAGE_WAITLIST: 'MANAGE_WAITLIST',
} as const;

type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

// Role-to-permissions mapping
const rolePermissions: Record<UserRole, Permission[]> = {
  SUPERADMIN: [
    // All permissions
    PERMISSIONS.CREATE_USER,
    PERMISSIONS.READ_USERS,
    PERMISSIONS.UPDATE_USER,
    PERMISSIONS.DELETE_USER,
    PERMISSIONS.CREATE_STUDENT,
    PERMISSIONS.READ_STUDENTS,
    PERMISSIONS.UPDATE_STUDENT,
    PERMISSIONS.DELETE_STUDENT,
    PERMISSIONS.CREATE_COURSE,
    PERMISSIONS.READ_COURSES,
    PERMISSIONS.UPDATE_COURSE,
    PERMISSIONS.DELETE_COURSE,
    PERMISSIONS.CREATE_PROGRAM,
    PERMISSIONS.READ_PROGRAMS,
    PERMISSIONS.UPDATE_PROGRAM,
    PERMISSIONS.DELETE_PROGRAM,
    PERMISSIONS.CREATE_CLASS,
    PERMISSIONS.READ_CLASSES,
    PERMISSIONS.UPDATE_CLASS,
    PERMISSIONS.DELETE_CLASS,
    PERMISSIONS.ASSIGN_TEACHER,
    PERMISSIONS.CREATE_TEACHER,
    PERMISSIONS.READ_TEACHERS,
    PERMISSIONS.UPDATE_TEACHER,
    PERMISSIONS.DELETE_TEACHER,
    PERMISSIONS.CREATE_ENROLLMENT,
    PERMISSIONS.READ_ENROLLMENTS,
    PERMISSIONS.UPDATE_ENROLLMENT,
    PERMISSIONS.DELETE_ENROLLMENT,
    PERMISSIONS.CREATE_COURSE_HISTORY,
    PERMISSIONS.READ_COURSE_HISTORY,
    PERMISSIONS.UPDATE_COURSE_HISTORY,
    PERMISSIONS.DELETE_COURSE_HISTORY,
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.MANAGE_WAITLIST,
  ],

  ADMIN: [
    // User management - NO
    // Students - full
    PERMISSIONS.CREATE_STUDENT,
    PERMISSIONS.READ_STUDENTS,
    PERMISSIONS.UPDATE_STUDENT,
    PERMISSIONS.DELETE_STUDENT,
    // Courses - full
    PERMISSIONS.CREATE_COURSE,
    PERMISSIONS.READ_COURSES,
    PERMISSIONS.UPDATE_COURSE,
    PERMISSIONS.DELETE_COURSE,
    // Programs - full
    PERMISSIONS.CREATE_PROGRAM,
    PERMISSIONS.READ_PROGRAMS,
    PERMISSIONS.UPDATE_PROGRAM,
    PERMISSIONS.DELETE_PROGRAM,
    // Classes - full
    PERMISSIONS.CREATE_CLASS,
    PERMISSIONS.READ_CLASSES,
    PERMISSIONS.UPDATE_CLASS,
    PERMISSIONS.DELETE_CLASS,
    PERMISSIONS.ASSIGN_TEACHER,
    // Teachers - full
    PERMISSIONS.CREATE_TEACHER,
    PERMISSIONS.READ_TEACHERS,
    PERMISSIONS.UPDATE_TEACHER,
    PERMISSIONS.DELETE_TEACHER,
    // Enrollments - full
    PERMISSIONS.CREATE_ENROLLMENT,
    PERMISSIONS.READ_ENROLLMENTS,
    PERMISSIONS.UPDATE_ENROLLMENT,
    PERMISSIONS.DELETE_ENROLLMENT,
    // Course History - full
    PERMISSIONS.CREATE_COURSE_HISTORY,
    PERMISSIONS.READ_COURSE_HISTORY,
    PERMISSIONS.UPDATE_COURSE_HISTORY,
    PERMISSIONS.DELETE_COURSE_HISTORY,
    // Dashboard - yes
    PERMISSIONS.VIEW_DASHBOARD,
    // Waitlist - yes
    PERMISSIONS.MANAGE_WAITLIST,
  ],

  STAFF: [
    // User management - NO
    // Students - full
    PERMISSIONS.CREATE_STUDENT,
    PERMISSIONS.READ_STUDENTS,
    PERMISSIONS.UPDATE_STUDENT,
    PERMISSIONS.DELETE_STUDENT,
    // Courses - read only
    PERMISSIONS.READ_COURSES,
    // Programs - read only
    PERMISSIONS.READ_PROGRAMS,
    // Classes - read only
    PERMISSIONS.READ_CLASSES,
    // Teachers - read only
    PERMISSIONS.READ_TEACHERS,
    // Enrollments - full
    PERMISSIONS.CREATE_ENROLLMENT,
    PERMISSIONS.READ_ENROLLMENTS,
    PERMISSIONS.UPDATE_ENROLLMENT,
    PERMISSIONS.DELETE_ENROLLMENT,
    // Course History - full
    PERMISSIONS.CREATE_COURSE_HISTORY,
    PERMISSIONS.READ_COURSE_HISTORY,
    PERMISSIONS.UPDATE_COURSE_HISTORY,
    PERMISSIONS.DELETE_COURSE_HISTORY,
    // Dashboard - yes
    PERMISSIONS.VIEW_DASHBOARD,
    // Waitlist - yes
    PERMISSIONS.MANAGE_WAITLIST,
  ],
};

export function hasPermission(role: UserRole | undefined, permission: Permission): boolean {
  if (!role || !rolePermissions[role]) {
    return false;
  }
  const permissions = rolePermissions[role];
  return Array.isArray(permissions) && permissions.includes(permission);
}

export function checkPermission(role: UserRole, permission: Permission): void {
  if (!hasPermission(role, permission)) {
    throw new Error(`User role '${role}' does not have permission: ${permission}`);
  }
}
